photo_6/config/routes.rb
Photo6::Application.routes.draw do
  resources :corgis

  root 'corgis#index'

end

photo_6/app/models/corgi.rb
class Corgi < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

photo_6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

photo_6/app/controllers/corgis_controller.rb
class CorgisController < ApplicationController
  before_action :set_corgi, only: [:show, :edit, :update, :destroy]

  # GET /corgis
  # GET /corgis.json
  def index
    @corgis = Corgi.all
  end

  # GET /corgis/1
  # GET /corgis/1.json
  def show
  end

  # GET /corgis/new
  def new
    @corgi = Corgi.new
  end

  # GET /corgis/1/edit
  def edit
  end

  # POST /corgis
  # POST /corgis.json
  def create
    @corgi = Corgi.new(corgi_params)

    respond_to do |format|
      if @corgi.save
        format.html { redirect_to @corgi, notice: 'Corgi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @corgi }
      else
        format.html { render action: 'new' }
        format.json { render json: @corgi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corgis/1
  # PATCH/PUT /corgis/1.json
  def update
    respond_to do |format|
      if @corgi.update(corgi_params)
        format.html { redirect_to @corgi, notice: 'Corgi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @corgi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corgis/1
  # DELETE /corgis/1.json
  def destroy
    @corgi.destroy
    respond_to do |format|
      format.html { redirect_to corgis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corgi
      @corgi = Corgi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corgi_params
      params.require(:corgi).permit(:name, :image)
    end
end

photo_6/app/helpers/application_helper.rb
module ApplicationHelper
end

photo_6/app/helpers/corgis_helper.rb
module CorgisHelper
end

photo_6/app/views/corgis/_form.html.erb
<%= form_for@corgi, :html => {:multipart => true} do |f| %>
  <% if @corgi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corgi.errors.count, "error") %> prohibited this corgi from being saved:</h2>

      <ul>
      <% @corgi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

photo_6/app/views/corgis/edit.html.erb
<h1>Editing corgi</h1>

<%= render 'form' %>

<%= link_to 'Show', @corgi %> |
<%= link_to 'Back', corgis_path %>

photo_6/app/views/corgis/index.html.erb
<h1>Listing lots of corgis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @corgis.each do |corgi| %>
      <tr>
        <td><%= corgi.name %></td>
        <td><%= image_tag corgi.image_url, :size => "200x200"  %></td>
        <td><%= link_to 'Show', corgi %></td>
        <td><%= link_to 'Edit', edit_corgi_path(corgi) %></td>
        <td><%= link_to 'Destroy', corgi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corgi', new_corgi_path %>

photo_6/app/views/corgis/new.html.erb
<h1>New corgi</h1>

<%= render 'form' %>

<%= link_to 'Back', corgis_path %>

photo_6/app/views/corgis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @corgi.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@corgi.image_url, :width =>200, :height=>200) %>
</p>

<%= link_to 'Edit', edit_corgi_path(@corgi) %> |
<%= link_to 'Back', corgis_path %>

photo_6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>